### ISSUE TITLE
Change Vsix to offer VS 2019 and VS 2022 support

### ISSUE THREAD

**Issue by mrtank** [dotnet-websharper/templates#36]
Modify the current versions in Vsix to VS 2019 and VS 2022. Drop support for VS 2017

**Comment by mrtank** [comment]
I have to fix to Any CPU and fix `Microsoft.VisualStudio.Community` to amd64 architecture. Follow https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022 steps

**Comment by mrtank** [comment]
Without Microsoft.VSSDK.BuildTools upgraded to 17.x version running the VSIX didn't even offer integration to 2022. Are you sure it's working?

**Comment by granicz** [comment]
As of WebSharper 6, no VSIX installers are published - please use the `dotnet` CLI to install WebSharper project templates; these will then show up in Visual Studio (check [here](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/) for more details).
